### ISSUE TITLE
Assets folder not being added to Dist on gulp build

### ISSUE THREAD

**Issue by mckeever02** [sondr3/generator-jekyllized#115] opened 2016-03-23 18:14 UTC
Hi sondr3,

So I've ran into another issue thats basically making it impossible for me to use jekyllized, which sucks, because I love it. 

Anytime I run gulp build, all of the files and folders are added to dist, except assets. If I watch the folder in finder then run it I can see the assets folder being added, and then promptly removed. Any ideas why this is happening?

**Comment by sondr3** [comment] 2016-03-24 17:04
Really? What version of the generator are you using? I thought I had fixed this problem a while ago.

**Comment by mckeever02** [comment] 2016-03-25 08:33
I'm using `1.7.0` Not sure if thats the latest version or not

**Comment by mckeever02** [comment] 2016-03-25 08:46
Yay! It seems updating to the latest version of git has solved this.

**Comment by mckeever02** [comment] 2016-03-29 10:06
Actually it seems updating to the latest version hasn't fixed the issue. I think I have figured out the cause however. 

It seems I can only get the assets folder to compile when jekyll isn't running. If I try `gulp build` when gulp is running the assets folder is added and then removed. If I stop jekyll and then run the command, the assets folder is compiled successfully. 

Any idea why this would be happening?

**Comment by sondr3** [comment] 2016-03-29 10:32
Hmm, no idea, can you give me a repo where I can reproduce? This should be fixed a long time ago.

**Comment by sondr3** [comment] 2016-03-29 20:55
Or wait, are you running Jekyll alongside the gulp commands? It sounds like that from rereading your comment, that is not how you're supposed to run this generator. I have tried to reproduce this but I cannot figure out what could make that happen.

**Comment by mckeever02** [comment] 2016-03-30 09:40
Hey sondr3, No I mean if I run `gulp` and then try to `gulp build` the assets folder won't be added to dist, but if I stop all the `gulp` tasks and then run `gulp build` again, it will add the assets.

**Comment by mckeever02** [comment] 2016-03-30 09:48
Here's a repo of the project I'm experiencing the issue on: https://github.com/mckeever02/dental-solutions-test

**Comment by sondr3** [comment] 2016-03-30 11:47
You aren't supposed to run gulp build while you are running gulp either. It will auto generate everything you need running gulp. I'll take a look.

**Comment by sondr3** [comment] 2016-04-01 00:09
Not sure what your problem is, after running `gulp` and seeing the webpage be generated and all your assets compiled the folder structure looks like this:

```
dist/
├── about
├── archive
│   ├── 2014
│   │   └── 03
│   └── 2015
│       └── 02
├── assets
│   ├── images
│   │   └── touch
│   ├── javascript
│   └── stylesheets
├── category
│   ├── example
│   └── jekyll
└── jekyll
    └── example
```

By the way, you don't need to add either `Gemfile.lock`, `node_modules`, `bower_components`, `dist` or `.tmp` to git as all of those will be automatically installed regardless. However, I can't reproduce this. You should be able to run only `gulp` and it'll do everything required.

**Closed by sondr3** 2016-04-01 00:09 UTC
