### ISSUE TITLE
Jekyll deleting assets folder when running gulp build --prod with beta branch

### ISSUE THREAD

**Issue by nsbingham** [sondr3/generator-jekyllized#125] opened 2016-04-21 16:02 UTC
When running `gulp build --prod`, the `dist/assets` directory did not exist after the task completed. I believe I narrowed it down to jekyll cleaning out any files in the destination directory that it doesn't recognize. I found that adding `keep_files: ['assets']` to `_config.yml`. I wasn't having the issue when running the `gulp default` task without the `--prod` flag, so I tried to put it in the `_config.build.yml`, but this did not work.

I'd submit a PR with the updated template, but the fact that it didn't work in the `_config.build.yml` made me wonder if it's more of a race condition. Is anyone else having trouble with the `gulp build --prod` task?

Running
```
OSX 10.11.4 (15E65)
Node 4.4.3
NPM 2.15.1
yo 1.7.0
jekyll 3.1.2
```

**Comment by sondr3** [comment] 2016-04-21 16:10
I'll be home from Prague this Saturday, so I'll take a look. But that sounds like a strange problem since the `jekyll` task completes before the `assets` folder is even started. I'll look into it.

**Comment by sondr3** [comment] 2016-04-24 15:18
You haven't figured out anything more? I've tried this at home but can't reproduce at all.

**Comment by nsbingham** [comment] 2016-04-25 15:04
@sondr3 adding `keep_files: ['assets']` to `_config.yml` fixed the issue for me though I'm not sure why it is happening. I did a fresh install of jekyllized in a new project it works as expected without the `keep_files`, so I'm not sure what I changed to cause this to happen. If I figure it out, I'll update this thread, but I think this issue is probably mine and not jekyllized now.

**Comment by sondr3** [comment] 2016-04-25 16:26
That's really weird, yeah, haha. But I guess that can happen occasionally. I'll close this issue for now then :)

**Closed by sondr3** 2016-04-25 16:26 UTC
Labels: cannot-reproduce
