### ISSUE TITLE
JavaScript files not being created in when using gulp-deploy

### ISSUE THREAD

**Issue by antonioOrtiz** [sondr3/generator-jekyllized#75] opened 2015-03-01 18:15 UTC
It appears the JS files are not getting copied over for the PROD build. This works when serving to preview locally, (I get a javascript folder with all my files unminified) but again not when you're ready to run gulp-deploy. Is it something in the `_config.yml` file?

**Comment by sondr3** [comment] 2015-03-01 18:18
Do you have anywhere I could take a look at the code? I'm not really sure what could do it but I'll definitely take a look.

**Comment by antonioOrtiz** [comment] 2015-03-01 18:21
https://github.com/antonioOrtiz/antonioortiz.github.io
antonio-p-ortiz.com
That's my repo where I am deploying...
Thank you!

**Comment by sondr3** [comment] 2015-03-01 18:24
Yeah, but I need to look at the development code, not the deployment code. If you could push your dev code to either a different branch or a different repo that'd be neat.

**Comment by antonioOrtiz** [comment] 2015-03-01 18:34
I am sorry, should have realized that!
https://github.com/antonioOrtiz/antonioortiz.github.io/tree/devCodeForBlog

**Comment by antonioOrtiz** [comment] 2015-03-01 18:37
Weird. I noticed when creating the branch for the DEV files a `assets` was created with a `javascript` folder in it with a minified version of my `js` files...

**Comment by sondr3** [comment] 2015-03-01 19:00
I'm pretty sure that the problem is that you have added the `{{ site.baseurl }}` to the JavaScript build comment in the default layout. That'll mess up how it generate the folders, try removing it and running it again.

**Comment by antonioOrtiz** [comment] 2015-03-01 20:11
It worked! Thanks!!!!!!!!

**Comment by sondr3** [comment] 2015-03-01 20:28
No worries, glad to hear it works! Let me know if you need help with anything else. I'll close this one for now as it's fixed :smiley:

**Closed by sondr3** 2015-03-01 20:28 UTC
